/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import codigos.Resolve;
import java.awt.Color;
import java.awt.Font;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gustavo
 */
public class IUprincipal extends javax.swing.JFrame {

    private ViewPanel view;
    private Resolve resolve;
    private boolean inicializado; // Informa se o usuário embaralhou o tabuleiro

    /**
     * Creates new form IUprincipal
     */
    public IUprincipal() {
        this.view = new ViewPanel();
        this.inicializado = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JScrollPane(this.view);
        Menu = new javax.swing.JMenuBar();
        Tab_menu = new javax.swing.JMenu();
        Iniciar_tab_menu = new javax.swing.JMenuItem();
        Embaralhar_menu = new javax.swing.JMenuItem();
        Resolver_menu = new javax.swing.JMenu();
        Cega_menu = new javax.swing.JMenuItem();
        Heuristica1_menu = new javax.swing.JMenuItem();
        Heuristica2_menu = new javax.swing.JMenuItem();
        HPessoal_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab_menu.setText("Tabuleiro");

        Iniciar_tab_menu.setText("Iniciar Tabuleiro");
        Iniciar_tab_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_tab_menuActionPerformed(evt);
            }
        });
        Tab_menu.add(Iniciar_tab_menu);

        Embaralhar_menu.setText("Embaralhar");
        Embaralhar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Embaralhar_menuActionPerformed(evt);
            }
        });
        Tab_menu.add(Embaralhar_menu);

        Menu.add(Tab_menu);

        Resolver_menu.setText("Resolver");

        Cega_menu.setText("Busca Cega");
        Cega_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cega_menuActionPerformed(evt);
            }
        });
        Resolver_menu.add(Cega_menu);

        Heuristica1_menu.setText("Heurística 1");
        Heuristica1_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heuristica1_menuActionPerformed(evt);
            }
        });
        Resolver_menu.add(Heuristica1_menu);

        Heuristica2_menu.setText("Heurística 2");
        Heuristica2_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heuristica2_menuActionPerformed(evt);
            }
        });
        Resolver_menu.add(Heuristica2_menu);

        HPessoal_menu.setText("Heurística Pessoal");
        HPessoal_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPessoal_menuActionPerformed(evt);
            }
        });
        Resolver_menu.add(HPessoal_menu);

        Menu.add(Resolver_menu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iniciar_tab_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_tab_menuActionPerformed
        int dimensao = Integer.valueOf(JOptionPane.showInputDialog("Insira qual a dimensão do tabuleiro"));
        this.resolve = new Resolve(dimensao, dimensao);
        this.view.setTab(this.resolve);
        this.inicializado = true;
        this.Panel.repaint();
    }//GEN-LAST:event_Iniciar_tab_menuActionPerformed

    private void Embaralhar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Embaralhar_menuActionPerformed
        if (this.inicializado) {
            int movimentos = Integer.valueOf(JOptionPane.showInputDialog("Insira o número de movimentos"));
            this.resolve.embaralha(movimentos);
            this.view.setTab(resolve);
            this.view.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Inicialize o tabuleiro!");
        }
    }//GEN-LAST:event_Embaralhar_menuActionPerformed

    private void Cega_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cega_menuActionPerformed
        if (this.inicializado) {
            this.resolve.buscaCega();
            this.view.setTab(this.resolve);
            this.view.repaint();

        } else {
            JOptionPane.showMessageDialog(this, "Inicialize o tabuleiro!");
        }
    }//GEN-LAST:event_Cega_menuActionPerformed

    private void Heuristica1_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heuristica1_menuActionPerformed
        if (this.inicializado) {
            this.resolve.buscaH1();
            this.view.setTab(this.resolve);
            this.view.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Inicialize o tabuleiro!");
        }
    }//GEN-LAST:event_Heuristica1_menuActionPerformed

    private void Heuristica2_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heuristica2_menuActionPerformed
        if (this.inicializado) {
            this.resolve.buscaH2();
            this.view.setTab(this.resolve);
            this.view.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Inicialize o tabuleiro!");
        }
    }//GEN-LAST:event_Heuristica2_menuActionPerformed

    private void HPessoal_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPessoal_menuActionPerformed
        if (this.inicializado) {
            this.resolve.buscaHPessoal();
            this.view.setTab(this.resolve);
            this.view.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Inicialize o tabuleiro!");
        }
    }//GEN-LAST:event_HPessoal_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUprincipal().setVisible(true);
            }
        });
    }

    public class ViewPanel extends JPanel {

        private Resolve tabuleiro;

        public void setTab(Resolve tab) {
            this.tabuleiro = tab;
        }

        @Override
        public void paintComponent(java.awt.Graphics g) {
            if (this.tabuleiro == null) {
                return;
            }

            int alturaPanel = this.getHeight();
            int larguraPanel = this.getWidth();
            int[][] aux = this.tabuleiro.getTab();

            int linhas = this.tabuleiro.getLin();
            int colunas = this.tabuleiro.getCol();

            super.paintComponent(g);
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;

            this.setBackground(Color.lightGray);

            // configuração do rendering para obeter melhor qualidade
            g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
            g2.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
            g2.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);

            int larguras = larguraPanel / linhas;
            int alturas = alturaPanel / linhas;

            larguras = larguraPanel / linhas;
            alturas = alturaPanel / colunas;
            g2.setStroke(new java.awt.BasicStroke(5f));
            g2.setColor(Color.black);
            g2.setFont(new Font("TimesRoman", Font.PLAIN, larguras / 10));

            for (int i = 0; i < linhas; i++) {
                for (int j = 0; j < colunas; j++) {
                    // Desenha o quadrado branco que se movimenta
                    if (aux[i][j] == -1) {
                        g2.setColor(Color.white);
                        g2.fillRect(j * larguras, i * alturas,
                                larguras, alturas);
                        g2.setColor(Color.black);
                        continue;
                    }
                    g2.drawString(String.valueOf(aux[i][j] + 1), (j * 2 + 1)
                            * (larguras / 2), (i * 2 + 1) * (alturas / 2));
                }
            }
            g2.setStroke(new java.awt.BasicStroke(1f));
            g2.setColor(Color.black);
            for (int i = 1; i < linhas; i++) {
                // Desenha as colunas
                g2.drawLine(i * larguras, 0, i * larguras, alturaPanel);

                // Desenha as linhas
                g2.drawLine(0, i * alturas, larguraPanel, i * alturas);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cega_menu;
    private javax.swing.JMenuItem Embaralhar_menu;
    private javax.swing.JMenuItem HPessoal_menu;
    private javax.swing.JMenuItem Heuristica1_menu;
    private javax.swing.JMenuItem Heuristica2_menu;
    private javax.swing.JMenuItem Iniciar_tab_menu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JScrollPane Panel;
    private javax.swing.JMenu Resolver_menu;
    private javax.swing.JMenu Tab_menu;
    // End of variables declaration//GEN-END:variables
}
